apiVersion: v1
kind: Secret
metadata:
  name: zq2-stake-frontend
  namespace: zq2-stake-stg-prototestnet
  labels:
    app.kubernetes.io/name: zq2-stake-frontend
  annotations:
    zilliqa.com/autofill: prj-d-staging
type: Opaque
data:
  ZQ2_STAKING_WALLET_CONNECT_API_KEY: "zq2-staking-prototestnet/WALLET_CONNECT_API_KEY"
