project_id: prj-p-prod-apps-3cidxzuc
bastion_instance_name: vm-p-prod-apps-bastion-ase1
bastion_instance_zone: asia-southeast1-a
region: asia-southeast1

k8s_clusters:
  production:
    project_id: "prj-p-prod-apps-3cidxzuc"
    name: gke-p-prod-apps-01-ase1

registry: asia-docker.pkg.dev/prj-p-devops-services-tvwmrf63/zilliqa-private

dbs_to_instances:
  - names:
      - service: main/zq2-staking/zq2-staking-frontend
        db_user: op://prj-p-prod-apps/zq2-staking-protomainnet/username
        db_user_password: op://prj-p-prod-apps/zq2-staking-protomainnet/password
    cluster:
      name: zq2-staking-protomainnet
      address: 10.110.2.49
      admin:
        username: op://prj-p-prod-apps/zq2-staking-protomainnet/root_username
        password: op://prj-p-prod-apps/zq2-staking-protomainnet/root_password

apps_to_clusters:
  - name_re: main/zq2-staking/zq2-staking-frontend
    cluster: production
    dns_name: stake.zq2-protomainnet.zilliqa.com
    healthcheck:
      request_path: /api/health
    image_name: zq2-staking-frontend
    namespace: zq2-staking-protomainnet
    pipeline:
      dockerfile_path: images/frontend/Dockerfile
      context: .
    replicas: 1
    env_vars:
      - name: ZQ2_STAKING_CHAIN_ID
        value: 32770
    pod_limits:
      cpu: 200m
      memory: 200Mi
    pod_requests:
      cpu: 100m
      memory: 100Mi

secrets:
  zq2_staking:
    wallet_connect_api_key:
      _op: "op://prj-p-prod-apps/zq2-staking-protomainnet/WALLET_CONNECT_API_KEY"
