apiVersion: apps/v1
kind: Deployment
metadata:
  name: zq2-stake-frontend
  namespace: zq2-stake
  labels:
    app.kubernetes.io/name: zq2-stake-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zq2-stake-frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zq2-stake-frontend
    spec:
      containers:
        - image: zq2-staking-frontend
          name: zq2-staking-frontend
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 100Mi
          env:
            - name: ZQ2_STAKING_CHAIN_ID
              valueFrom:
                configMapKeyRef:
                  name: zq2-stake-frontend
                  key: ZQ2_STAKING_CHAIN_ID
            - name: ZQ2_STAKING_WALLET_CONNECT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: zq2-stake-frontend
                  key: ZQ2_STAKING_WALLET_CONNECT_API_KEY
            - name: ZQ2_STAKING_INTERCOM_KEY
              valueFrom:
                secretKeyRef:
                  name: zq2-stake-frontend
                  key: ZQ2_STAKING_INTERCOM_KEY
            - name: ZQ2_STAKING_APP_URL
              valueFrom:
                configMapKeyRef:
                  name: zq2-stake-frontend
                  key: ZQ2_STAKING_APP_URL
            - name: ZQ2_STAKING_GTM_ID
              valueFrom:
                secretKeyRef:
                  name: zq2-stake-frontend
                  key: ZQ2_STAKING_GTM_ID
            - name: ZQ2_PREVIEW_SECRET_HASH
              valueFrom:
                secretKeyRef:
                  name: zq2-stake-frontend
                  key: ZQ2_PREVIEW_SECRET_HASH
