apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: zq2-stake-frontend
  namespace: zq2-stake-frontend
  labels:
    app.kubernetes.io/name: zq2-stake-frontend
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        requestPath: /api/health
        port: 3000
  targetRef:
    group: ""
    kind: Service
    name: zq2-stake-frontend
