apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: zq2-stake-frontend
  namespace: zq2-stake-prd-mainnet-preview
  labels:
    app.kubernetes.io/name: zq2-stake-frontend
spec:
  domains:
    - stake-preview.zilliqa.com
