name: "CICD production"

on:
  # On released
  release:
    types: [published]

jobs:
  build-docker:
    permissions:
      id-token: write
      contents: write
      security-events: write
    runs-on: ubuntu-22.04
    name: "Deploy image"
    strategy:
      fail-fast: false
      matrix:
        application:
          - zq2-staking-frontend
        include:
          - application: zq2-staking-frontend
            image_name: zq2-staking-frontend
            file: images/frontend/Dockerfile
            context: .
    env:
      DOCKER_DOMAIN: asia-docker.pkg.dev
      REGISTRY: asia-docker.pkg.dev/prj-p-devops-services-tvwmrf63/zilliqa-public
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: "true"
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0

      - name: Docker build and push - production
        uses: Zilliqa/gh-actions-workflows/actions/ci-dockerized-app-build-push@v4
        with:
          file: ${{ matrix.file }}
          context: ${{ matrix.context }}
          push: true
          tag: ${{ env.REGISTRY }}/${{ matrix.image_name }}:${{ github.ref_name }}
          registry: asia-docker.pkg.dev
          workload-identity-provider: "${{ secrets.GCP_PRD_GITHUB_WIF }}"
          service-account: "${{ secrets.GCP_PRD_GITHUB_SA_DOCKER_REGISTRY }}"
          cache-key: ${{ env.REGISTRY }}/${{ matrix.image_name }}-cache
          trivy-scan: true
          build-args: |
            DEPLOY_ENV=prd
